# NumPy paskaita

[nuoroda i kurso medziaga](https://github.com/robotautas/kursas/blob/master/NumPy/numpy.ipynb)

### importuojami daiktai

In [109]:
import numpy as np

nustatom neribota eilutes ilgi, skaiciu po kablelio tiksluma...

In [110]:
np.set_printoptions(linewidth=np.inf, precision=2)

In [111]:
listas = [5, 3, 1, 7, 9]
listas

[5, 3, 1, 7, 9]

### masyvas

In [112]:
masyvas = np.array(listas)
masyvas

array([5, 3, 1, 7, 9])

In [113]:
eile = np.arange(1, 16, 2)
eile

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [114]:
nuliai = np.zeros(10, int)
nuliai

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Linear Space

In [115]:
paskirstyta = np.linspace(0, 10, 5)
paskirstyta

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [116]:
np.linspace(0, 16, 9)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16.])

### matrica

In [117]:
pirminis_listas = [[1, 2, 3], [6, 5, 4], [8, 9, 7]]
matrica = np.array(pirminis_listas)
matrica

array([[1, 2, 3],
       [6, 5, 4],
       [8, 9, 7]])

In [118]:
np.zeros((5, 5), int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [119]:
np.ones((3, 3), int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [120]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Random Masyvai ir Matricos

In [121]:
np.random.rand(10)

array([0.27, 0.35, 0.36, 0.54, 0.02, 0.42, 0.71, 0.19, 0.37, 0.72])

In [122]:
np.random.rand(5, 5)

array([[0.69, 0.01, 0.02, 0.49, 0.97],
       [0.78, 0.69, 0.19, 0.75, 0.28],
       [0.26, 0.96, 0.37, 0.2 , 0.51],
       [0.18, 0.69, 0.37, 0.41, 0.68],
       [0.11, 0.98, 0.84, 0.59, 0.44]])

In [123]:
np.random.randn(3, 3)

array([[-0.26,  0.49,  0.54],
       [ 0.61,  0.25, -1.44],
       [ 1.28, -0.24, -1.04]])

In [124]:
# masyvas
np.random.randint(100, 200, 17)

array([133, 145, 175, 185, 170, 143, 150, 179, 138, 164, 103, 142, 108, 119, 176, 199, 110])

In [125]:
# matrica
np.random.randint(100, 200, (7, 7))

array([[129, 130, 100, 158, 192, 184, 150],
       [123, 113, 145, 167, 181, 154, 190],
       [175, 107, 137, 115, 178, 153, 127],
       [162, 107, 129, 109, 120, 176, 146],
       [117, 115, 133, 181, 198, 154, 121],
       [130, 194, 167, 119, 158, 179, 187],
       [199, 139, 102, 161, 166, 127, 193]])

### Masyvu pertvarkymas

In [146]:
ilgas64 = np.random.randint(10, 100, 64)
ilgas64

array([97, 49, 60, 22, 81, 43, 26, 36, 26, 38, 88, 98, 70, 74, 72, 21, 86, 36, 25, 70, 19, 84, 17, 31, 51, 84, 16, 65, 48, 90, 46, 62, 41, 82, 20, 46, 68, 29, 29, 44, 54, 47, 33, 55, 55, 29, 16, 36, 61, 51, 15, 68, 55, 36, 25, 22, 84, 21, 11, 93, 36, 21, 99, 64])

In [147]:
matrica8x8 = ilgas64.reshape(8, 8)
matrica8x8

array([[97, 49, 60, 22, 81, 43, 26, 36],
       [26, 38, 88, 98, 70, 74, 72, 21],
       [86, 36, 25, 70, 19, 84, 17, 31],
       [51, 84, 16, 65, 48, 90, 46, 62],
       [41, 82, 20, 46, 68, 29, 29, 44],
       [54, 47, 33, 55, 55, 29, 16, 36],
       [61, 51, 15, 68, 55, 36, 25, 22],
       [84, 21, 11, 93, 36, 21, 99, 64]])

### Naudingi metodai

In [148]:
matrica8x8.min()

11

In [149]:
matrica8x8.argmin()

array([[58]], dtype=int64)

In [150]:
matrica8x8.max()

99

In [151]:
matrica8x8.argmax()

array([[62]], dtype=int64)