# NumPy paskaita

[nuoroda i kurso medziaga](https://github.com/robotautas/kursas/blob/master/NumPy/numpy.ipynb)

### importuojan numpy

In [1]:
import numpy as np

In [5]:
listas = [5, 3, 1, 7, 9]
listas

[5, 3, 1, 7, 9]

### masyvas

In [7]:
masyvas = np.array(listas)
masyvas

array([5, 3, 1, 7, 9])

In [16]:
eile = np.arange(1, 16, 2)
eile

array([ 5, 12])

In [13]:
nuliai = np.zeros(100)
nuliai

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### matrica

In [9]:
pirminis_listas = [[1, 2, 3], [6, 5, 4], [8, 9, 7]]
matrica = np.array(pirminis_listas)
matrica

array([[1, 2, 3],
       [6, 5, 4],
       [8, 9, 7]])