# NumPy paskaita

[nuoroda i kurso medziaga](https://github.com/robotautas/kursas/blob/master/NumPy/numpy.ipynb)

### importuojami daiktai

In [34]:
import numpy as np

In [5]:
listas = [5, 3, 1, 7, 9]
listas

[5, 3, 1, 7, 9]

### masyvas

In [7]:
masyvas = np.array(listas)
masyvas

array([5, 3, 1, 7, 9])

In [17]:
eile = np.arange(1, 16, 2)
eile

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [20]:
nuliai = np.zeros(10, int)
nuliai

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Linear Space

In [28]:
paskirstyta = np.linspace(0, 10, 5)
paskirstyta

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
np.linspace(0, 16, 9)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16.])

### matrica

In [9]:
pirminis_listas = [[1, 2, 3], [6, 5, 4], [8, 9, 7]]
matrica = np.array(pirminis_listas)
matrica

array([[1, 2, 3],
       [6, 5, 4],
       [8, 9, 7]])

In [22]:
np.zeros((5, 5), int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
np.ones((3, 3), int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])