# NumPy paskaita

[nuoroda i kurso medziaga](https://github.com/robotautas/kursas/blob/master/NumPy/numpy.ipynb)

### importuojami daiktai

In [182]:
import numpy as np

nustatom neribota eilutes ilgi, skaiciu po kablelio tiksluma...

In [183]:
np.set_printoptions(linewidth=np.inf, precision=2)

In [184]:
listas = [5, 3, 1, 7, 9]
listas

[5, 3, 1, 7, 9]

### masyvas

In [185]:
masyvas = np.array(listas)
masyvas

array([5, 3, 1, 7, 9])

In [186]:
eile = np.arange(1, 16, 2)
eile

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [187]:
nuliai = np.zeros(10, int)
nuliai

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Linear Space

In [188]:
paskirstyta = np.linspace(0, 10, 5)
paskirstyta

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [189]:
np.linspace(0, 16, 9)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16.])

### matrica

In [190]:
pirminis_listas = [[1, 2, 3], [6, 5, 4], [8, 9, 7]]
matrica = np.array(pirminis_listas)
matrica

array([[1, 2, 3],
       [6, 5, 4],
       [8, 9, 7]])

In [191]:
np.zeros((5, 5), int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [192]:
np.ones((3, 3), int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [193]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Random Masyvai ir Matricos

In [194]:
np.random.rand(10)

array([0.12, 0.9 , 0.36, 0.24, 0.7 , 0.12, 0.41, 0.3 , 0.78, 0.81])

In [195]:
np.random.rand(5, 5)

array([[0.27, 0.37, 0.1 , 0.7 , 0.18],
       [0.55, 0.05, 0.12, 0.7 , 0.8 ],
       [0.95, 0.95, 0.36, 0.04, 0.07],
       [0.52, 0.12, 0.4 , 0.44, 0.78],
       [0.97, 0.69, 0.22, 0.9 , 0.55]])

In [196]:
np.random.randn(3, 3)

array([[ 0.55, -1.56,  0.23],
       [-2.64,  0.08,  0.17],
       [ 3.02,  1.21,  0.18]])

In [197]:
# masyvas
np.random.randint(100, 200, 17)

array([103, 125, 136, 106, 128, 109, 177, 116, 187, 164, 166, 146, 148, 135, 193, 104, 110])

In [198]:
# matrica
np.random.randint(100, 200, (7, 7))

array([[145, 109, 185, 153, 141, 197, 162],
       [113, 170, 144, 126, 155, 188, 118],
       [191, 102, 187, 132, 188, 171, 129],
       [183, 174, 122, 105, 132, 147, 165],
       [135, 113, 157, 189, 151, 131, 142],
       [171, 117, 174, 125, 193, 128, 162],
       [121, 169, 123, 192, 111, 132, 155]])

### Masyvu pertvarkymas

In [199]:
ilgas64 = np.random.randint(10, 100, 64)
ilgas64

array([39, 76, 56, 92, 89, 75, 19, 67, 19, 23, 59, 11, 46, 14, 48, 56, 53, 99, 46, 33, 87, 72, 47, 17, 72, 44, 88, 54, 42, 40, 71, 53, 44, 30, 83, 68, 46, 95, 84, 95, 30, 13, 97, 23, 53, 31, 88, 22, 84, 31, 88, 99, 14, 54, 69, 86, 66, 75, 27, 18, 96, 43, 81, 78])

In [200]:
matrica8x8 = ilgas64.reshape(8, 8)
matrica8x8

array([[39, 76, 56, 92, 89, 75, 19, 67],
       [19, 23, 59, 11, 46, 14, 48, 56],
       [53, 99, 46, 33, 87, 72, 47, 17],
       [72, 44, 88, 54, 42, 40, 71, 53],
       [44, 30, 83, 68, 46, 95, 84, 95],
       [30, 13, 97, 23, 53, 31, 88, 22],
       [84, 31, 88, 99, 14, 54, 69, 86],
       [66, 75, 27, 18, 96, 43, 81, 78]])

### Naudingi metodai

In [201]:
matrica8x8.min()

11

In [202]:
matrica8x8.argmin()

11

In [203]:
matrica8x8.max()

99

In [204]:
matrica8x8.argmax()

17

In [205]:
matrica8x8.shape

(8, 8)

In [206]:
matrica8x8.dtype

dtype('int32')

### Indeksacija ir reiksmiu traukimas

#### is masyvo

In [207]:
ilgas64[5]

75

In [208]:
ilgas64[17:33]

array([99, 46, 33, 87, 72, 47, 17, 72, 44, 88, 54, 42, 40, 71, 53, 44])

In [209]:
ilgas64[::4].reshape(4, 4)

array([[39, 89, 19, 46],
       [53, 87, 72, 42],
       [44, 46, 30, 53],
       [84, 14, 66, 96]])

In [210]:
ilgas64[-5] # nuo galo

18

In [211]:
kreivas64 = ilgas64.copy()
kreivas64[::4] = 77
kreivas64

array([77, 76, 56, 92, 77, 75, 19, 67, 77, 23, 59, 11, 77, 14, 48, 56, 77, 99, 46, 33, 77, 72, 47, 17, 77, 44, 88, 54, 77, 40, 71, 53, 77, 30, 83, 68, 77, 95, 84, 95, 77, 13, 97, 23, 77, 31, 88, 22, 77, 31, 88, 99, 77, 54, 69, 86, 77, 75, 27, 18, 77, 43, 81, 78])

#### is matricos

In [217]:
matrica8x8

array([[39, 76, 56, 92, 89, 75, 19, 67],
       [19, 23, 59, 11, 46, 14, 48, 56],
       [53, 99, 46, 33, 87, 72, 47, 17],
       [72, 44, 88, 54, 42, 40, 71, 53],
       [44, 30, 83, 68, 46, 95, 84, 95],
       [30, 13, 97, 23, 53, 31, 88, 22],
       [84, 31, 88, 99, 14, 54, 69, 86],
       [66, 75, 27, 18, 96, 43, 81, 78]])

In [213]:
matrica8x8[4, 2]

83

In [214]:
matrica8x8[1:7, 1:7]

array([[23, 59, 11, 46, 14, 48],
       [99, 46, 33, 87, 72, 47],
       [44, 88, 54, 42, 40, 71],
       [30, 83, 68, 46, 95, 84],
       [13, 97, 23, 53, 31, 88],
       [31, 88, 99, 14, 54, 69]])

In [215]:
matrica8x8[-3:, -3:]

array([[31, 88, 22],
       [54, 69, 86],
       [43, 81, 78]])

In [181]:
matrica8x8[:3, -3:]

array([[43, 26, 36],
       [74, 72, 21],
       [84, 17, 31]])

### Salyginis traukimas

In [219]:
matrica8x8

array([[39, 76, 56, 92, 89, 75, 19, 67],
       [19, 23, 59, 11, 46, 14, 48, 56],
       [53, 99, 46, 33, 87, 72, 47, 17],
       [72, 44, 88, 54, 42, 40, 71, 53],
       [44, 30, 83, 68, 46, 95, 84, 95],
       [30, 13, 97, 23, 53, 31, 88, 22],
       [84, 31, 88, 99, 14, 54, 69, 86],
       [66, 75, 27, 18, 96, 43, 81, 78]])

In [224]:
virs70 = matrica8x8 >= 70
virs70

array([[False,  True, False,  True,  True,  True, False, False],
       [False, False, False, False, False, False, False, False],
       [False,  True, False, False,  True,  True, False, False],
       [ True, False,  True, False, False, False,  True, False],
       [False, False,  True, False, False,  True,  True,  True],
       [False, False,  True, False, False, False,  True, False],
       [ True, False,  True,  True, False, False, False,  True],
       [False,  True, False, False,  True, False,  True,  True]])

In [225]:
matrica8x8[virs70]

array([76, 92, 89, 75, 99, 87, 72, 72, 88, 71, 83, 95, 84, 95, 97, 88, 84, 88, 99, 86, 75, 96, 81, 78])

In [226]:
matrica8x8[matrica8x8 > 90]

array([92, 99, 95, 95, 97, 99, 96])

#### python native

In [234]:
from random import randint
eilute = []
for i in range(0, 100):
    eilute.append(randint(10, 100))

eilute # [eilute > 50] neveiks

[46,
 73,
 42,
 53,
 34,
 85,
 22,
 80,
 17,
 67,
 81,
 48,
 29,
 90,
 60,
 12,
 66,
 26,
 66,
 76,
 30,
 98,
 27,
 47,
 60,
 99,
 82,
 90,
 28,
 90,
 39,
 40,
 88,
 62,
 41,
 78,
 32,
 43,
 86,
 60,
 91,
 45,
 38,
 63,
 35,
 31,
 87,
 86,
 88,
 63,
 83,
 34,
 89,
 56,
 53,
 44,
 47,
 31,
 93,
 79,
 90,
 70,
 74,
 73,
 28,
 84,
 100,
 65,
 96,
 88,
 91,
 68,
 97,
 35,
 52,
 67,
 91,
 72,
 12,
 29,
 43,
 96,
 62,
 34,
 25,
 82,
 85,
 90,
 75,
 60,
 98,
 57,
 12,
 47,
 89,
 16,
 10,
 89,
 64,
 30]

### Numpy elgsenos ipatumai

In [235]:
pvz = np.random.randint(1, 21, 20)
pvz

array([ 4, 10, 12,  9,  4, 18, 13,  8, 19, 19, 19,  6, 13,  7, 15,  9, 18, 18, 18, 10])

In [237]:
ispjova = pvz[5:15]
ispjova

array([18, 13,  8, 19, 19, 19,  6, 13,  7, 15])

In [239]:
ispjova[:] = 99
ispjova

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [246]:
pvz

array([ 4, 10, 12,  9,  4, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,  9, 18, 18, 18, 10])

In [247]:
pvzc = pvz.copy()
pvzc

array([ 4, 10, 12,  9,  4, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,  9, 18, 18, 18, 10])

In [248]:
pvzc == pvz

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True])

In [249]:
pvzc_ispjova = pvzc[5:15]
pvzc_ispjova[:] = 77
pvzc

array([ 4, 10, 12,  9,  4, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77,  9, 18, 18, 18, 10])

In [250]:
pvz

array([ 4, 10, 12,  9,  4, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77,  9, 18, 18, 18, 10])