# NumPy paskaita

[nuoroda i kurso medziaga](https://github.com/robotautas/kursas/blob/master/NumPy/numpy.ipynb)

### importuojami daiktai

In [2]:
import numpy as np

nustatom neribota eilutes ilgi, skaiciu po kablelio tiksluma...

In [3]:
np.set_printoptions(linewidth=np.inf, precision=2)

In [4]:
listas = [5, 3, 1, 7, 9]
listas

[5, 3, 1, 7, 9]

### masyvas

In [5]:
masyvas = np.array(listas)
masyvas

array([5, 3, 1, 7, 9])

In [6]:
eile = np.arange(1, 16, 2)
eile

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [7]:
nuliai = np.zeros(10, int)
nuliai

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Linear Space

In [8]:
paskirstyta = np.linspace(0, 10, 5)
paskirstyta

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
np.linspace(0, 16, 9)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16.])

### matrica

In [10]:
pirminis_listas = [[1, 2, 3], [6, 5, 4], [8, 9, 7]]
matrica = np.array(pirminis_listas)
matrica

array([[1, 2, 3],
       [6, 5, 4],
       [8, 9, 7]])

In [11]:
np.zeros((5, 5), int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
np.ones((3, 3), int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Random Masyvai ir Matricos

In [14]:
np.random.rand(10)

array([0.13, 0.78, 0.98, 0.08, 0.13, 1.  , 0.56, 0.51, 0.65, 0.2 ])

In [15]:
np.random.rand(5, 5)

array([[0.88, 0.04, 0.3 , 0.64, 0.86],
       [0.43, 0.28, 0.76, 0.79, 0.71],
       [0.94, 0.98, 0.5 , 0.17, 0.09],
       [0.13, 0.23, 0.71, 0.68, 0.42],
       [0.64, 0.  , 0.75, 0.22, 0.45]])

In [16]:
np.random.randn(3, 3)

array([[-1.94, -1.07, -0.22],
       [-0.34, -1.38,  0.29],
       [-0.57,  2.34,  0.3 ]])

In [17]:
# masyvas
np.random.randint(100, 200, 17)

array([142, 105, 199, 126, 173, 107, 124, 157, 185, 143, 147, 198, 167, 106, 127, 134, 108])

In [18]:
# matrica
np.random.randint(100, 200, (7, 7))

array([[130, 169, 160, 122, 167, 177, 168],
       [105, 180, 158, 103, 158, 183, 188],
       [110, 155, 117, 117, 147, 119, 134],
       [150, 169, 103, 160, 135, 117, 160],
       [152, 156, 151, 147, 134, 124, 168],
       [109, 171, 166, 109, 167, 103, 125],
       [198, 124, 144, 189, 194, 141, 160]])

### Masyvu pertvarkymas

In [19]:
ilgas64 = np.random.randint(10, 100, 64)
ilgas64

array([30, 58, 31, 62, 77, 22, 47, 32, 36, 48, 81, 44, 82, 11, 30, 17, 61, 35, 71, 56, 21, 20, 91, 94, 81, 27, 79, 78, 79, 65, 60, 23, 45, 77, 82, 15, 93, 44, 29, 72, 91, 64, 58, 77, 56, 63, 69, 22, 95, 52, 66, 27, 41, 43, 52, 42, 74, 61, 19, 58, 64, 24, 48, 11])

In [20]:
matrica8x8 = ilgas64.reshape(8, 8)
matrica8x8

array([[30, 58, 31, 62, 77, 22, 47, 32],
       [36, 48, 81, 44, 82, 11, 30, 17],
       [61, 35, 71, 56, 21, 20, 91, 94],
       [81, 27, 79, 78, 79, 65, 60, 23],
       [45, 77, 82, 15, 93, 44, 29, 72],
       [91, 64, 58, 77, 56, 63, 69, 22],
       [95, 52, 66, 27, 41, 43, 52, 42],
       [74, 61, 19, 58, 64, 24, 48, 11]])

### Naudingi metodai

In [21]:
matrica8x8.min()

11

In [22]:
matrica8x8.argmin()

13

In [23]:
matrica8x8.max()

95

In [24]:
matrica8x8.argmax()

48

In [25]:
matrica8x8.shape

(8, 8)

In [26]:
matrica8x8.dtype

dtype('int32')

### Indeksacija ir reiksmiu traukimas

#### is masyvo

In [27]:
ilgas64[5]

22

In [28]:
ilgas64[17:33]

array([35, 71, 56, 21, 20, 91, 94, 81, 27, 79, 78, 79, 65, 60, 23, 45])

In [29]:
ilgas64[::4].reshape(4, 4)

array([[30, 77, 36, 82],
       [61, 21, 81, 79],
       [45, 93, 91, 56],
       [95, 41, 74, 64]])

In [30]:
ilgas64[-5] # nuo galo

58

In [31]:
kreivas64 = ilgas64.copy()
kreivas64[::4] = 77
kreivas64

array([77, 58, 31, 62, 77, 22, 47, 32, 77, 48, 81, 44, 77, 11, 30, 17, 77, 35, 71, 56, 77, 20, 91, 94, 77, 27, 79, 78, 77, 65, 60, 23, 77, 77, 82, 15, 77, 44, 29, 72, 77, 64, 58, 77, 77, 63, 69, 22, 77, 52, 66, 27, 77, 43, 52, 42, 77, 61, 19, 58, 77, 24, 48, 11])

#### is matricos

In [32]:
matrica8x8

array([[30, 58, 31, 62, 77, 22, 47, 32],
       [36, 48, 81, 44, 82, 11, 30, 17],
       [61, 35, 71, 56, 21, 20, 91, 94],
       [81, 27, 79, 78, 79, 65, 60, 23],
       [45, 77, 82, 15, 93, 44, 29, 72],
       [91, 64, 58, 77, 56, 63, 69, 22],
       [95, 52, 66, 27, 41, 43, 52, 42],
       [74, 61, 19, 58, 64, 24, 48, 11]])

In [33]:
matrica8x8[4, 2]

82

In [34]:
matrica8x8[1:7, 1:7]

array([[48, 81, 44, 82, 11, 30],
       [35, 71, 56, 21, 20, 91],
       [27, 79, 78, 79, 65, 60],
       [77, 82, 15, 93, 44, 29],
       [64, 58, 77, 56, 63, 69],
       [52, 66, 27, 41, 43, 52]])

In [35]:
matrica8x8[-3:, -3:]

array([[63, 69, 22],
       [43, 52, 42],
       [24, 48, 11]])

In [36]:
matrica8x8[:3, -3:]

array([[22, 47, 32],
       [11, 30, 17],
       [20, 91, 94]])

### Salyginis traukimas

In [37]:
matrica8x8

array([[30, 58, 31, 62, 77, 22, 47, 32],
       [36, 48, 81, 44, 82, 11, 30, 17],
       [61, 35, 71, 56, 21, 20, 91, 94],
       [81, 27, 79, 78, 79, 65, 60, 23],
       [45, 77, 82, 15, 93, 44, 29, 72],
       [91, 64, 58, 77, 56, 63, 69, 22],
       [95, 52, 66, 27, 41, 43, 52, 42],
       [74, 61, 19, 58, 64, 24, 48, 11]])

In [38]:
virs70 = matrica8x8 >= 70
virs70

array([[False, False, False, False,  True, False, False, False],
       [False, False,  True, False,  True, False, False, False],
       [False, False,  True, False, False, False,  True,  True],
       [ True, False,  True,  True,  True, False, False, False],
       [False,  True,  True, False,  True, False, False,  True],
       [ True, False, False,  True, False, False, False, False],
       [ True, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False]])

In [39]:
matrica8x8[virs70]

array([77, 81, 82, 71, 91, 94, 81, 79, 78, 79, 77, 82, 93, 72, 91, 77, 95, 74])

In [40]:
matrica8x8[matrica8x8 > 90]

array([91, 94, 93, 91, 95])

#### python native

In [41]:
from random import randint
eilute = []
for i in range(0, 100):
    eilute.append(randint(10, 100))

eilute # [eilute > 50] neveiks

[19,
 39,
 51,
 19,
 72,
 25,
 60,
 30,
 17,
 68,
 73,
 60,
 27,
 95,
 45,
 98,
 56,
 18,
 84,
 30,
 61,
 44,
 26,
 36,
 57,
 14,
 63,
 92,
 44,
 39,
 45,
 12,
 23,
 27,
 30,
 89,
 39,
 15,
 47,
 47,
 86,
 48,
 27,
 40,
 81,
 18,
 84,
 98,
 40,
 70,
 53,
 69,
 85,
 66,
 91,
 25,
 15,
 45,
 43,
 67,
 95,
 66,
 98,
 68,
 14,
 92,
 98,
 49,
 45,
 29,
 93,
 99,
 90,
 11,
 57,
 93,
 29,
 100,
 64,
 41,
 51,
 89,
 36,
 51,
 27,
 97,
 57,
 41,
 87,
 60,
 58,
 55,
 30,
 29,
 28,
 80,
 13,
 13,
 97,
 21]

### Numpy elgsenos ipatumai

In [42]:
pvz = np.random.randint(1, 21, 20)
pvz

array([ 8, 12, 14, 18,  3,  8, 15, 13,  2,  7,  6,  7,  4,  2,  5, 19,  5,  6,  7, 17])

In [43]:
ispjova = pvz[5:15]
ispjova

array([ 8, 15, 13,  2,  7,  6,  7,  4,  2,  5])

In [44]:
ispjova[:] = 99
ispjova

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [45]:
pvz

array([ 8, 12, 14, 18,  3, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 19,  5,  6,  7, 17])

In [46]:
pvzc = pvz.copy()
pvzc

array([ 8, 12, 14, 18,  3, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 19,  5,  6,  7, 17])

In [47]:
pvzc == pvz

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True])

In [48]:
pvzc_ispjova = pvzc[5:15]
pvzc_ispjova[:] = 77
pvzc

array([ 8, 12, 14, 18,  3, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 19,  5,  6,  7, 17])

In [49]:
pvz

array([ 8, 12, 14, 18,  3, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 19,  5,  6,  7, 17])

### matematines funkcijos

In [50]:
vektoriux = np.arange(1, 11)
vektoriux

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
vektoriux * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [52]:
vektoriux * vektoriux

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [53]:
dvigubas_vektoriux = vektoriux + vektoriux
dvigubas_vektoriux

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [54]:
vektoriux / 15

array([0.07, 0.13, 0.2 , 0.27, 0.33, 0.4 , 0.47, 0.53, 0.6 , 0.67])

In [55]:
vektoriux ** vektoriux

array([         1,          4,         27,        256,       3125,      46656,     823543,   16777216,  387420489, 1410065408])

In [56]:
np.sin(vektoriux)

array([ 0.84,  0.91,  0.14, -0.76, -0.96, -0.28,  0.66,  0.99,  0.41, -0.54])

In [57]:
np.cos(vektoriux)

array([ 0.54, -0.42, -0.99, -0.65,  0.28,  0.96,  0.75, -0.15, -0.91, -0.84])

In [58]:
np.tan(vektoriux)

array([ 1.56, -2.19, -0.14,  1.16, -3.38, -0.29,  0.87, -6.8 , -0.45,  0.65])

In [59]:
np.log(vektoriux ** vektoriux)

array([ 0.  ,  1.39,  3.3 ,  5.55,  8.05, 10.75, 13.62, 16.64, 19.78, 21.07])